name: bienestar_animal
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core  
  auto_route: ^4.2.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  dartz: ^0.10.1
  get_it: ^7.2.0
  connectivity_plus: ^2.2.1
  validators: ^3.0.0
  flutter_smart_dialog: ^3.4.0+1
  device_preview: ^1.0.0
  location: ^4.2.0
  google_maps_flutter: ^2.1.8
  google_maps_flutter_web: ^0.4.0
  flutter_markdown: ^0.6.10+2

  # Storage
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^5.0.2

  # Beauty
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  cached_network_image: ^3.2.1
  im_stepper: ^1.0.1+1
  dropdown_search: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  auto_route_generator: ^4.2.0



flutter:
  uses-material-design: true

